name: Test Python package

"on": push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./.github/release.requirements.txt
          pip install -r ./.github/test.requirements.txt
      - name: autoflake
        run: |
          autoflake \
          --in-place \
          --remove-all-unused-imports \
          --remove-unused-variables \
          --recursive .
      - run: black .
      - run: isort .
      - uses: peter-evans/create-pull-request@v7
        with:
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          commit-message: 'fix: CI suggestion'
          branch: 'patch/${{ github.ref_name }}'
          title: 'CI: Suggestion for ${{ github.ref_name }}'
          sign-commits: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./.github/release.requirements.txt
      - name: Create dummy version file
        run: |
          cat <<EOF > "src/RPIoTlogger/version.py"
          # This is ONLY for test deployment
          __version__ = '0.0.0'
          # $GITHUB_REPOSITORY $GITHUB_RUN_ID
          # $(date +'%Y-%m-%d %H:%M:%S')
          EOF
      - name: Build package
        run: |
          python setup.py sdist
          rm dist/*.orig
      - name: Test built package
        run: twine check dist/*
