name: Test Python package

on:
  push:
    branches-ignore:
      - "main"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install twine setuptools
          if [ -f requirements-test.txt ]; then pip install -r ./.github/requirements-test.txt; fi
      - name: Create dummy version file
        run: |
          cat <<EOF > "src/RPIoTlogger/version.py"
          # This is ONLY for test deployment
          __version__ = '0.0.0'
          # $GITHUB_REPOSITORY $GITHUB_RUN_ID
          # $(date +'%Y-%m-%d %H:%M:%S')
          EOF
      - name: Build package
        run: |
          python setup.py sdist
          rm dist/*.orig
      - name: Test built package
        run: |
          twine check dist/*

  autoflake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: creyD/autoflake_action@v1.1
        with:
          options: --in-place --remove-all-unused-imports --remove-unused-variables -r

  formatter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--diff"
      - uses: isort/isort-action@v1
        with:
          configuration: "--diff"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Code Formatter Change

