name: Test Python package

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 twine setuptools black
          if [ -f requirements-test.txt ]; then pip install -r ./.github/requirements-test.txt; fi

      - uses: reviewdog/action-flake8@v3
        with:
          reporter: github-check
          level: warning

      - uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-check
          yamllint_flags: "-c ./.github/.yamllint ./.github/workflows/*.yml"
          level: warning

      - uses: reviewdog/action-black@v3
        with:
          reporter: github-check
          level: warning

      - name: Create dummy version file
        run: |
          cat <<EOF > "src/RPIoTlogger/version.py"
          # This is ONLY for test deployment
          __version__ = '0.0.0'
          # $GITHUB_REPOSITORY $GITHUB_RUN_ID
          # $(date +'%Y-%m-%d %H:%M:%S')
          EOF

      - name: Build package
        run: |
          python setup.py sdist
          rm dist/*.orig

      - name: Test built package
        run: |
          twine check dist/*

