name: Unittest Python Package

on: [push]

permissions:
  contents: read

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # all history is needed to crawl it properly
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install nose2 pytest coverage
          if [ -f requirements-test.txt ]; then pip install -r ./.github/requirements-test.txt; fi

      - name: Execute tests
        run: |
          python create_report_dirs.py
          nose2 --config tests/unittest.cfg

      - name: Create coverage report
        run: |
          coverage xml
          echo '## Coverage' >> $GITHUB_STEP_SUMMARY
          cat .reports/coverage/coverage.xml >> $GITHUB_STEP_SUMMARY

