name: YAML Lint

"on": push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yamllint
          if [ -f requirements-test.txt ]; \
            then pip install -r ./.github/requirements-test.txt; \
          fi
      - name: yamllint
        run: |
          yamllint \
          --format github \
          -c ./.github/.yamllint .
